import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });


export default function RootLayout({children}: { children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
          <main>
            {children}
          </main>
      </body>
    </html>
  );
}
